import { ColumnDataType, HeaderTableProps } from './table.constant';

function makeData() {
  return [
    {
      firstName: 'window',
      lastName: 1940,
      age: 11,
      visits: 85,
      progress: 72,
      status: 1940,
      subRows: [
        {
          firstName: 'square',
          lastName: 'leadership',
          age: 29,
          visits: 43,
          progress: 36,
          status: 'complicated',
        },
        {
          firstName: 'low',
          lastName: 'flight',
          age: 16,
          visits: 94,
          progress: 25,
          status: 'relationship',
        },
        {
          firstName: 'kittens',
          lastName: 'recess',
          age: 28,
          visits: 93,
          progress: 73,
          status: 'single',
        },
        {
          firstName: 'election',
          lastName: 'glove',
          age: 16,
          visits: 11,
          progress: 17,
          status: 'single',
        },
        {
          firstName: 'morning',
          lastName: 'pigs',
          age: 4,
          visits: 56,
          progress: 81,
          status: 'single',
        },
      ],
    },
    {
      firstName: 'committee',
      lastName: 'performance',
      age: 26,
      visits: 18,
      progress: 91,
      status: 'single',
      subRows: [
        {
          firstName: 'airplane',
          lastName: 'chickens',
          age: 13,
          visits: 13,
          progress: 24,
          status: 'relationship',
        },
        {
          firstName: 'rake',
          lastName: 'ship',
          age: 11,
          visits: 64,
          progress: 24,
          status: 'relationship',
        },
        {
          firstName: 'calculator',
          lastName: 'mode',
          age: 21,
          visits: 96,
          progress: 35,
          status: 'single',
        },
        {
          firstName: 'field',
          lastName: 'effect',
          age: 10,
          visits: 43,
          progress: 23,
          status: 'complicated',
        },
        {
          firstName: 'basket',
          lastName: 'dogs',
          age: 18,
          visits: 10,
          progress: 32,
          status: 'relationship',
        },
      ],
    },
    {
      firstName: 'beer',
      lastName: 'spiders',
      age: 10,
      visits: 8,
      progress: 10,
      status: 'complicated',
      subRows: [
        {
          firstName: 'homework',
          lastName: 'people',
          age: 28,
          visits: 17,
          progress: 69,
          status: 'relationship',
        },
        {
          firstName: 'account',
          lastName: 'car',
          age: 10,
          visits: 23,
          progress: 1,
          status: 'single',
        },
        {
          firstName: 'tendency',
          lastName: 'walk',
          age: 3,
          visits: 32,
          progress: 76,
          status: 'single',
        },
        {
          firstName: 'furniture',
          lastName: 'fishing',
          age: 4,
          visits: 65,
          progress: 59,
          status: 'single',
        },
        {
          firstName: 'swing',
          lastName: 'cart',
          age: 4,
          visits: 49,
          progress: 99,
          status: 'relationship',
        },
      ],
    },
    {
      firstName: 'volume',
      lastName: 'kittens',
      age: 25,
      visits: 54,
      progress: 32,
      status: 'relationship',
      subRows: [
        {
          firstName: 'smile',
          lastName: 'daughter',
          age: 12,
          visits: 68,
          progress: 51,
          status: 'complicated',
        },
        {
          firstName: 'speaker',
          lastName: 'lettuce',
          age: 9,
          visits: 69,
          progress: 47,
          status: 'single',
        },
        {
          firstName: 'weather',
          lastName: 'winner',
          age: 18,
          visits: 86,
          progress: 94,
          status: 'complicated',
        },
        {
          firstName: 'stomach',
          lastName: 'turkey',
          age: 27,
          visits: 3,
          progress: 59,
          status: 'relationship',
        },
        {
          firstName: 'veil',
          lastName: 'cat',
          age: 18,
          visits: 7,
          progress: 45,
          status: 'single',
        },
      ],
    },
    {
      firstName: 'girls',
      lastName: 'worm',
      age: 20,
      visits: 34,
      progress: 27,
      status: 'relationship',
      subRows: [
        {
          firstName: 'sir',
          lastName: 'technology',
          age: 22,
          visits: 63,
          progress: 55,
          status: 'relationship',
        },
        {
          firstName: 'tradition',
          lastName: 'team',
          age: 27,
          visits: 42,
          progress: 7,
          status: 'relationship',
        },
        {
          firstName: 'sleet',
          lastName: 'tail',
          age: 2,
          visits: 20,
          progress: 43,
          status: 'complicated',
        },
        {
          firstName: 'lift',
          lastName: 'wrench',
          age: 25,
          visits: 35,
          progress: 29,
          status: 'single',
        },
        {
          firstName: 'wind',
          lastName: 'feet',
          age: 6,
          visits: 0,
          progress: 93,
          status: 'single',
        },
      ],
    },
  ];
}

function makeHeader() {
  const tableConfig: HeaderTableProps[] = [
    {
      columnHeader: 'First name',
      columnName: 'firstName',
      columnType: ColumnDataType.TEXT,
      columnSetting: {},
    },
    {
      columnHeader: 'Last name',
      columnName: 'lastName',
      columnType: ColumnDataType.SELECT_PICKER,
      columnSetting: {},
    },
    {
      columnHeader: 'Age',
      columnName: 'age',
      columnType: ColumnDataType.SELECT_PICKER,
      columnSetting: { readonly: true },
    },
    {
      columnHeader: 'Progress',
      columnName: 'progress',
      columnType: ColumnDataType.SELECT_PICKER,
    },
    {
      columnHeader: 'Status',
      columnName: 'status',
      columnType: ColumnDataType.SELECT_PICKER,
      columnSetting: {},
    },
    {
      columnHeader: 'Progress1',
      columnName: 'progress2',
      columnType: ColumnDataType.TEXT,
      columnSetting: {},
    },
    {
      columnHeader: 'Status2',
      columnName: 'status2',
      columnType: ColumnDataType.TEXT,
      columnSetting: {},
    },
  ];

  return tableConfig;
}
const top100Films = [
  { textValue: 'The Shawshank Redemption', idValue: 1994 },
  { textValue: 'The Godfather', idValue: 1972 },
  { textValue: 'The Godfather: Part II', idValue: 1974 },
  { textValue: 'The Dark Knight', idValue: 2008 },
  { textValue: '12 Angry Men', idValue: 1957 },
  { textValue: "Schindler's List", idValue: 1993 },
  { textValue: 'Pulp Fiction', idValue: 1994 },
  { textValue: 'The Lord of the Rings: The Return of the King', idValue: 2003 },
  { textValue: 'The Good, the Bad and the Ugly', idValue: 1966 },
  { textValue: 'Fight Club', idValue: 1999 },
  {
    textValue: 'The Lord of the Rings: The Fellowship of the Ring',
    idValue: 2001,
  },
  {
    textValue: 'Star Wars: Episode V - The Empire Strikes Back',
    idValue: 1980,
  },
  { textValue: 'Forrest Gump', idValue: 1994 },
  { textValue: 'Inception', idValue: 2010 },
  { textValue: 'The Lord of the Rings: The Two Towers', idValue: 2002 },
  { textValue: "One Flew Over the Cuckoo's Nest", idValue: 1975 },
  { textValue: 'Goodfellas', idValue: 1990 },
  { textValue: 'The Matrix', idValue: 1999 },
  { textValue: 'Seven Samurai', idValue: 1954 },
  { textValue: 'Star Wars: Episode IV - A New Hope', idValue: 1977 },
  { textValue: 'City of God', idValue: 2002 },
  { textValue: 'Se7en', idValue: 1995 },
  { textValue: 'The Silence of the Lambs', idValue: 1991 },
  { textValue: "It's a Wonderful Life", idValue: 1946 },
  { textValue: 'Life Is Beautiful', idValue: 1997 },
  { textValue: 'The Usual Suspects', idValue: 1995 },
  { textValue: 'Léon: The Professional', idValue: 1994 },
  { textValue: 'Spirited Away', idValue: 2001 },
  { textValue: 'Saving Private Ryan', idValue: 1998 },
  { textValue: 'Once Upon a Time in the West', idValue: 1968 },
  { textValue: 'American History X', idValue: 1998 },
  { textValue: 'Interstellar', idValue: 2014 },
  { textValue: 'Casablanca', idValue: 1942 },
  { textValue: 'City Lights', idValue: 1931 },
  { textValue: 'Psycho', idValue: 1960 },
  { textValue: 'The Green Mile', idValue: 1999 },
  { textValue: 'The Intouchables', idValue: 2011 },
  { textValue: 'Modern Times', idValue: 1936 },
  { textValue: 'Raiders of the Lost Ark', idValue: 1981 },
  { textValue: 'Rear Window', idValue: 1954 },
  { textValue: 'The Pianist', idValue: 2002 },
  { textValue: 'The Departed', idValue: 2006 },
  { textValue: 'Terminator 2: Judgment Day', idValue: 1991 },
  { textValue: 'Back to the Future', idValue: 1985 },
  { textValue: 'Whiplash', idValue: 2014 },
  { textValue: 'Gladiator', idValue: 2000 },
  { textValue: 'Memento', idValue: 2000 },
  { textValue: 'The Prestige', idValue: 2006 },
  { textValue: 'The Lion King', idValue: 1994 },
  { textValue: 'Apocalypse Now', idValue: 1979 },
  { textValue: 'Alien', idValue: 1979 },
  { textValue: 'Sunset Boulevard', idValue: 1950 },
  {
    textValue:
      'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    idValue: 1964,
  },
  { textValue: 'The Great Dictator', idValue: 1940 },
  { textValue: 'Cinema Paradiso', idValue: 1988 },
  { textValue: 'The Lives of Others', idValue: 2006 },
  { textValue: 'Grave of the Fireflies', idValue: 1988 },
  { textValue: 'Paths of Glory', idValue: 1957 },
  { textValue: 'Django Unchained', idValue: 2012 },
  { textValue: 'The Shining', idValue: 1980 },
  { textValue: 'WALL·E', idValue: 2008 },
  { textValue: 'American Beauty', idValue: 1999 },
  { textValue: 'The Dark Knight Rises', idValue: 2012 },
  { textValue: 'Princess Mononoke', idValue: 1997 },
  { textValue: 'Aliens', idValue: 1986 },
  { textValue: 'Oldboy', idValue: 2003 },
  { textValue: 'Once Upon a Time in America', idValue: 1984 },
  { textValue: 'Witness for the Prosecution', idValue: 1957 },
  { textValue: 'Das Boot', idValue: 1981 },
  { textValue: 'Citizen Kane', idValue: 1941 },
  { textValue: 'North by Northwest', idValue: 1959 },
  { textValue: 'Vertigo', idValue: 1958 },
  { textValue: 'Star Wars: Episode VI - Return of the Jedi', idValue: 1983 },
  { textValue: 'Reservoir Dogs', idValue: 1992 },
  { textValue: 'Braveheart', idValue: 1995 },
  { textValue: 'M', idValue: 1931 },
  { textValue: 'Requiem for a Dream', idValue: 2000 },
  { textValue: 'Amélie', idValue: 2001 },
  { textValue: 'A Clockwork Orange', idValue: 1971 },
  { textValue: 'Like Stars on Earth', idValue: 2007 },
  { textValue: 'Taxi Driver', idValue: 1976 },
  { textValue: 'Lawrence of Arabia', idValue: 1962 },
  { textValue: 'Double Indemnity', idValue: 1944 },
  { textValue: 'Eternal Sunshine of the Spotless Mind', idValue: 2004 },
  { textValue: 'Amadeus', idValue: 1984 },
  { textValue: 'To Kill a Mockingbird', idValue: 1962 },
  { textValue: 'Toy Story 3', idValue: 2010 },
  { textValue: 'Logan', idValue: 2017 },
  { textValue: 'Full Metal Jacket', idValue: 1987 },
  { textValue: 'Dangal', idValue: 2016 },
  { textValue: 'The Sting', idValue: 1973 },
  { textValue: '2001: A Space Odyssey', idValue: 1968 },
  { textValue: "Singin' in the Rain", idValue: 1952 },
  { textValue: 'Toy Story', idValue: 1995 },
  { textValue: 'Bicycle Thieves', idValue: 1948 },
  { textValue: 'The Kid', idValue: 1921 },
  { textValue: 'Inglourious Basterds', idValue: 2009 },
  { textValue: 'Snatch', idValue: 2000 },
  { textValue: '3 Idiots', idValue: 2009 },
  { textValue: 'Monty Python and the Holy Grail', idValue: 1975 },
];

export { makeData, makeHeader, top100Films };
